name: Deno

on:
  push:
  pull_request:

jobs:
  denofmt-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno lint
      - run: deno fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno cache *.ts
      - run: deno check *.ts

  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno task bundle

      - name: Package tar.gz
        run: >
          tar -cv
          -C public/ .
          | gzip --best > 6-2-1-rules.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: |
            *.tar.gz
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
