name: vite

on:
  push:
  pull_request:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Package tar.gz
        run: >
          tar -cv
          -C dist/ .
          | gzip --best > 6-2-1-rules.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: |
            *.tar.gz
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz